config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stations 
  resources :trains
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/station.rb
class Station < ApplicationRecord
	validates :name, presence: true, uniqueness: true

	has_many :train_stations  
	has_many :trains, through: :train_stations
	has_many :train_times

	def self.search(search)
		if search
			where(['name LIKE ?', "%#{search}%"])
		else
			#all.limit(2)
		end
	end
end

app/models/train.rb
class Train < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	
	has_many :train_stations 
	has_many :stations, through: :train_stations 
	has_many :train_times
end

app/models/train_station.rb
class TrainStation < ApplicationRecord
	belongs_to :train
	belongs_to :station
end

app/models/train_time.rb
class TrainTime < ApplicationRecord
	validates :arrival, presence: true
	validates	:departure, presence: true

	belongs_to :station
	belongs_to :train
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	require 'time'
	require 'date'
	helper_method :custom_duration_to_hours_mn_sec_str, :range_of_current_to_two_hour_later, :admin?, :day_of_weak

	def custom_duration_to_hours_mn_sec_str(duration)
	  hr, min = duration.divmod(60)
	  total_in_minutes = hr.hours + min.minutes 
	  Time.at(total_in_minutes).utc.strftime("%H:%M")
	end
	
	def range_of_current_to_two_hour_later
		time = Time.new
		current_time = (time.hour)*60 + time.min
		two_hour_after_current = current_time + (2*60)
		a = (current_time..two_hour_after_current).to_a
	end

	def current_day_of_week
		t = Time.at(Time.now)
		t.wday
	end

	def admin?
		current_user.admin?
	end

	def authorize_admin
    redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
  end

  def day_of_weak(weak_number)
  	a = weak_number.to_i
  	w1 = Date::DAYNAMES[a]
  	w2 = w1[0, 3]
  	# day = ->num { Date::DAYNAMES[num] } 
  	# day.(a).length
		# Date::DAYNAMES[weak_number]
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :authorize_admin, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_station, only: %i[ show edit update destroy ]

  def index
    if params[:search]
      @stations = Station.search(params[:search])
    else
      @stations = Station.all
    end
  end

  def show
    @station = Station.find(params[:id])
    @response = TrainTimePresenter.new(@station)
  end

  def new
    @station = Station.new
  end

  def edit
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      redirect_to station_path(@station)
      flash[:notice] = "Train was successfully created."
    else
      render 'new'
      flash[:notice] = "There is something wrong."
    end
  end

  def update
    if @station.update(station_params)
      redirect_to station_path(@station)
      flash[:notice] = "Station was successfully updated." 
    else
      render 'edit'
      flash[:notice] = "There is something wrong."
    end
  end

  def destroy
    @station.destroy
    redirect_to stations_path
    flash[:notice] = "Station was successfully destroyed."
  end

  private

    def set_station
      @station = Station.find(params[:id])
    end

    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :authorize_admin, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_train, only: %i[ show edit update destroy ]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to train_path(@train)
      flash[:notice] = "Train was successfully created."
    else
      render 'new'
      flash[:notice] = "There is something wrong."
    end
  end

  def update
    if @train.update(train_params)
      redirect_to train_path(@train)
      flash[:notice] = "Train was successfully updated."
    else
      render 'edit'
      flash[:notice] = "There is something wrong."
    end
  end

  def destroy
    if @train.destroy
      redirect_to trains_path
      flash[:notice] = "Train was successfully destroyed."
    end
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "My Train", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Stations", stations_path, class: "nav-link active" %>
        </li>

        <% if user_signed_in?  %>
          <li class="nav-item pt-2">
            Logged in <strong><%= current_user.email %></strong>
          </li>             
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link active' %>
          </li> 
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link active'  %>
          </li>

          <% if admin? %>
            <li class="nav-item">
              <%= link_to 'Create Station', new_station_path, class: 'nav-link active' %>
            </li> 
            <li class="nav-item">
              <%= link_to 'Create Train', new_train_path, class: 'nav-link active' %>
            </li> 
          <% end %>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link active'  %>
          </li> 
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:'nav-link active'  %>
          </li>
        <% end %>
        
      </ul>
      <li class="nav-item pb-3">
        <%= form_tag stations_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Station", class: "form-control"  %>
      </li>
          <%= submit_tag 'Search', class: "btn btn-outline-success pt-2 ", :name => nil %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindMyTrain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_route.html.erb
<table class="table">
  <thead>
    <tr class="bg-info">
      <th>Arrival Time</th>
      <th>Route</th>
      <th>Departure Time</th>
    </tr>
  </thead>

  <tbody>
    <% obj.stations.each do |station|%>
      <% obj.train_times.each do |train_time1| %>
        <% station.train_times.each do |train_time2| %>
          <% if train_time1 == train_time2  %>
            <tr>
              <td><%= custom_duration_to_hours_mn_sec_str(train_time1.arrival) %></td>
              <td class="bg-success"><%= station.name %></td>
              <td><%= custom_duration_to_hours_mn_sec_str(train_time1.departure) %></td>      
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:
      </h2>

      <ul>
        <% station.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>
        <div class="p-3 mb-2 bg-info text-dark">
          <h1>Station name</h1>
          </div>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td>
          <%= link_to station.name, station, class: "btn btn-outline-secondary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="p-3 mb-2 bg-warning text-dark">
  Welcome to <%= @station.name.upcase %> Junction
</div>


<div class="row ">
  <div class="col-md-6 ">
    <h1 class="p-3 mb-2 bg-info text-dark">All Trains</h1>
    <table>
      <thead>
        <tr>
          <th>Arrival-Time</th>
          <th>Train-name</th>
          <th>Running</th>
          <th>Depature-Time</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <% (@response.train_time3).each do |train_time1| %>
          <tr>
            <td><%= custom_duration_to_hours_mn_sec_str(train_time1.arrival) %></td>
            <td><%= link_to train_time1.train.name, train_path(train_time1.train), class: "btn btn-outline-secondary" %></td>
            <% if (0..6).to_a.include? train_time1.week_day %>
              <td><%= day_of_weak(train_time1.week_day) %></td>
            <% else %>
              <td>Daily</td>
            <% end %>
            <td><%= custom_duration_to_hours_mn_sec_str(train_time1.departure) %></td>      
         </tr>
         <% end %>
      </tbody>
    </table>  
  </div>

  <div class="col-md-6 ">
    <h1 class="p-3 mb-2 bg-info text-dark">After Two Hours Later</h1>
    <table>
      <thead>
        <tr>
          <th>Arrival-Time</th>
          <th>Train-name</th>
          <th>Running</th>
          <th>Depature-Time</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% (@response.train_time3).each do |train_time1| %>
          <% if range_of_current_to_two_hour_later.include?(train_time1.arrival) && current_day_of_week == train_time1.week_day %>
            <tr>
              <td><%= custom_duration_to_hours_mn_sec_str(train_time1.arrival) %></td>
              <td><%= link_to train_time1.train.name, train_path(train_time1.train), class: "btn btn-outline-secondary" %></td>
              <% if (0..6).to_a.include? train_time1.week_day %>
                <td><%= day_of_weak(train_time1.week_day) %></td>
              <% else %>
                <td>Daily</td>
              <% end %>
              <td><%= custom_duration_to_hours_mn_sec_str(train_time1.departure) %></td>      
           </tr>
          <% end %>
       <% end %>
      </tbody>
    </table>  
  </div>
</div>


<div>
  <%= link_to 'Back', stations_path %>
</div>

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>
      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Trains</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= link_to train.name, train , class: "btn btn-outline-secondary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <div class="p-4 mb-2 bg-primary text-white "><%= @train.name %> Route</div>
  </div>
</div> 

<%= render "shared/route", obj: @train %>

app/views/welcome/index.html.erb
<div class="p-3 bg-info text-dark">
  <h1>Welcome to the Find-My-Train Portal</h1>
</div>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
    	<%= image_tag('t5.jpg', width: "100%") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Indian Trains</h5>
        <p>The right way to reach your Destiny.</p>
      </div>
    </div>
    <div class="carousel-item">
    	<%= image_tag('t6.jpg', width: "100%") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Lovely Journey</h5>
        <p>The place you like so much to travel.</p>
      </div>
    </div>
    <div class="carousel-item">
    	<%= image_tag('t7.jpg', width: "100%") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Luxury Travel</h5>
        <p>Sometimes, that light at the end of the tunnel is a train.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>